config/routes.rb
Rails.application.routes.draw do

  resources :authors, :books
  root 'authors#index'

end

app/models/author.rb
class Author < ActiveRecord::Base
	has_many :books

	def to_s
		"#{first_name} #{last_name}"
	end
end

app/models/book.rb
class Book < ActiveRecord::Base
  belongs_to :author
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  # 

end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_action :current_author, only: [:show, :edit, :update, :destroy]		
  respond_to :json

  def index
  	@authors = Author.all
  	render json: @authors
  end

  def show
  	render json: {author: @author, books: @author.books}
  end
  def new
  	@author = Author.new
  end
  def create
  	@author = Author.create(author_params)

  	render json: @author
  	# redirect_to author_path(@author)
  end

  def edit
  end

  def update
  	@author.update(author_params)
  	render json: @author
  	# redirect_to author_path(@author)
  end
  def destroy
  	@author.books.each do |book|
  		book.destroy
  	end
  	@author.destroy
  	# redirect_to authors_path
  end

  private
  def author_params
  	params.require(:author).permit(:first_name, :last_name)

  end
  def current_author
  	@author = Author.find(params[:id])
  end	
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
	before_action :current_book, only: [:show, :edit, :update, :destroy]
    respond_to :json
  def index
  	@books = Book.all
  	render json: @books
  end

  def show
  end

  def new
  	@book  = Book.new
  end
  def create
  	@book = Book.create(book_params)
  	render json: @book
  	# redirect_to book_path(@book)
  end

  def edit
  end
  def update
  	@book.update(book_params)
  	render json: @book
  	# redirect_to book_path(@book)
  end
  def destroy
  	@book.destroy
  	render json: @book
  	# redirect_to books_path
  end
  private
  def book_params
  	params.require(:book).permit(:title, :isbn, :description, :author_id)
  end	
  def current_book
  	@book = Book.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/authors/edit.html.erb
<h3>Edit Author</h3>
<%= form_for(@author) do |form| %>
	<p>First Name: <%= form.text_field :first_name %></p>
	<p>Last Name: <%= form.text_field :last_name %></p>
	<%= form.submit %>
<% end %>

app/views/authors/index.html.erb
<h1>List of Authors</h1>
<ul><% @authors.each do |author| %>
	<li>
		<%= link_to author.to_s, author_path(author) %>
	<% end %></li>
</ul>
<div><%= link_to 'Create Author', new_author_path %></div>		
<p><%= link_to 'View books by all author', books_path %></p>

app/views/authors/new.html.erb
<h3>Add Author</h3>
<%= form_for(@author) do |form| %>
	<p>First Name: <%= form.text_field :first_name %></p>
	<p>Last Name: <%= form.text_field :last_name %></p>
	<%= form.submit %>
<% end %>

app/views/authors/show.html.erb
<h1><%= @author.to_s %></h1>
<%= link_to 'Edit', edit_author_path(@author) %>
<h3>Books</h3>
<ul>
	<% @author.books.each do |book| %>
	<li><%= link_to book.title, book_path(book) %></li>
	<% end %>
</ul>
<br>
<p><%= link_to 'Add Book', new_book_path %></p>
<p><%= link_to 'Delete Author', @author,method: 'delete', data: {confirm: 'Are you sure?'}%></p>
<p><%= link_to 'Go back to all authors', authors_path %></p>

app/views/books/edit.html.erb
<h3>Edit Book</h3>
<%= form_for(@book) do |form| %>
  <p>Title: <%= form.text_field :title %></p>
  <p>ISBN: <%= form.text_field :isbn %></p>
  <p>Description: <%= form.text_field :description %></p>

  <p>Author: <%= form.select :author_id, Author.all.map { |author| [ author.to_s, author.id ] } %></p>
  <%= form.submit %>
<% end %>

app/views/books/index.html.erb
<h1>List of Books</h1>
<ul><% @books.each do |book| %>
  <li>
    <%= link_to book.title, book_path(book) %>
    <%= book.author %>
  <% end %></li>
</ul>

<div><%= link_to 'Add Book', new_book_path %></div>
<p><%= link_to 'Go back to authors page', authors_path %></p>

app/views/books/new.html.erb
<h3>Add Book</h3>
<%= form_for(@book) do |form| %>
  <p>Title: <%= form.text_field :title %></p>
  <p>ISBN: <%= form.text_field :isbn %></p>
  <p>Description: <%= form.text_field :description %></p>

  <p>Author: <%= form.select :author_id, Author.all.map { |author| [ author.to_s, author.id ] } %></p>
  <%= form.submit %>
<% end %>

app/views/books/show.html.erb
<h1><%= @book.title %></h1>
<%= link_to 'Edit', edit_book_path(@book) %>
<p><b>ISBN:</b> <%= @book.isbn %></p>
<p><b>Description:</b> <%= @book.description %></p>

<h4>Author: <%= link_to @book.author.to_s, author_path(@book.author) %></h4>

<p><%= link_to 'Delete', @book, method: 'delete', data: { confirm: 'Are you sure?' }%></p>
<p><%= link_to 'Go back to author page', author_path(@book.author) %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BooksWithAuthorsApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>